version: '3.3'

services:
  postgres-app:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "person_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - ./.db-init/:/docker-entrypoint-initdb.d/
